pruebas_index:
    path: /pruebas/index
    defaults: { _controller: AppBundle:Pruebas:index}
pruebas_create:
    path: /pruebas/create
    defaults: { _controller: AppBundle:Pruebas:create}
pruebas_read:
    path: /pruebas/read
    defaults: { _controller: AppBundle:Pruebas:read}
pruebas_update:
    path: /pruebas/update/{id}/{titulo}/{descripcion}/{precio}
    defaults: { _controller: AppBundle:Pruebas:update}